AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 900

Resources:

  MainLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: main.lambda_handler
      Runtime: python3.8
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
          - Action:
            - lambda:InvokeFunction
            - rds:CreateDBSnapshot
            - codepipeline:PutJobFailureResult
            - codepipeline:PutJobSuccessResult
            Effect: Allow
            Resource: '*'
